### PR TITLE
Fix for redundant compiles and incorrect version selection when running with solc_solcs_select flag 

### LINKED ISSUE #314: compile_all JSON object type error
I am running into an error when using crytic-compile:0.2.4 in a python project. When I call compile_all() on a directory, I get this error:
```
File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 164, in compile
    solc_handle_contracts(
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 328, in solc_handle_contracts
    json.loads(info["abi"]) if not is_above_0_8 else info["abi"]
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
```

### PR DESCRIPTION
**Pull request by indigo-eth-sec**
Added break statements to loops in _run_solcs_env and _run_solcs_path to return on first successful compilation instead of last. Also added consolidated compilation error outputs to allow for easier debugging.

When using a large range that includes earlier versions, this would sometimes select version 3.6, which causes other issues due to different output formats.

Fixes #314

### CODE REVIEW

**Comment by indigo-eth-sec** [comment]
Had some style issues and an incorrect variable reference. I fixed those in the latest commit.

**Comment by indigo-eth-sec** [comment]
Fixed further linter issues.

However, (ubuntu-latest, brownie) is failing due to this error "ConnectionError: Status 403 when retrieving repo brownie-mix/token information from GHAPI: 'API rate limit exceeded for 40.84.182.64."

And (windows-2022, etherscan) is failing due to this error "ERROR:CryticCompile:Contract has no public source code: https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0xcfc1E0968CA08aEe88CbF664D4A1f8B881d90f37
Etherscan test failed"

Please assist in resolving these two test errors, as they have nothing to do with these codes changes.

**Comment by 0xalpharush** [comment]
If you merge dev into your branch, it should address the errors from Brownie and Etherscan

**Comment by indigo-eth-sec** [comment]
Thanks. I merged dev into my branch and ran Black locally. This should pass now.

**Comment by montyly** [comment]
Hi @indigo-eth-sec. Thanks for the fix. We actually merged this PR up to `2a6eada` with https://github.com/crytic/crytic-compile/pull/346 2 days ago ;)

**Pull request closed without merging**
